name: Build and Release Launcher

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
  push:
    tags:
      - 'v*'

permissions:
  contents: write       # required to push tags/artifacts
  issues: write         # optional, not needed here
  pull-requests: write  # optional


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build launcher
        run: go build -o PancakeOSLauncher.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PancakeOSLauncher
          path: PancakeOSLauncher.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: PancakeOSLauncher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



