name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # Build the updater (Windows .exe)
      - name: Build updater
        working-directory: installer/installer/updater  # Correct path
        run: go build -o PancakeOSLauncher.exe

      # Upload the built artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PancakeOSLauncher
          path: installer/installer/updater/PancakeOSLauncher.exe

      # Create a GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: installer/installer/updater/PancakeOSLauncher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
