name: Build and Release Launcher

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git
        run: git tag v1.0.0 && git push origin v1.0.0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build launcher
        run: go build -o PancakeOSLauncher.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PancakeOSLauncher
          path: PancakeOSLauncher.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: PancakeOSLauncher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


